// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazDLBtLW2SwYUMyZuKzhfkB2TX23EsBc',
    appId: '1:989557975107:web:a646619c612f129c860cf6',
    messagingSenderId: '989557975107',
    projectId: 'oceanpet-7055d',
    authDomain: 'oceanpet-7055d.firebaseapp.com',
    storageBucket: 'oceanpet-7055d.firebasestorage.app',
    measurementId: 'G-J8P4NW9T5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEB4wkh1mxQM4ciNBtCJTk-XoTOy1bw2Q',
    appId: '1:989557975107:android:2f72b00a1a382946860cf6',
    messagingSenderId: '989557975107',
    projectId: 'oceanpet-7055d',
    storageBucket: 'oceanpet-7055d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhfGNsZKRAvTRPgXi2J0TALZbOEvx5J0',
    appId: '1:989557975107:ios:db1fd3fa159e9fb9860cf6',
    messagingSenderId: '989557975107',
    projectId: 'oceanpet-7055d',
    storageBucket: 'oceanpet-7055d.firebasestorage.app',
    androidClientId: '989557975107-s7tbirh1ptau7gltd32a7b3rc61s9t9c.apps.googleusercontent.com',
    iosClientId: '989557975107-n7usug5kcnbk1k9gmjuik40q6gvl7olc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oceanPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEhfGNsZKRAvTRPgXi2J0TALZbOEvx5J0',
    appId: '1:989557975107:ios:db1fd3fa159e9fb9860cf6',
    messagingSenderId: '989557975107',
    projectId: 'oceanpet-7055d',
    storageBucket: 'oceanpet-7055d.firebasestorage.app',
    androidClientId: '989557975107-s7tbirh1ptau7gltd32a7b3rc61s9t9c.apps.googleusercontent.com',
    iosClientId: '989557975107-n7usug5kcnbk1k9gmjuik40q6gvl7olc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oceanPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAazDLBtLW2SwYUMyZuKzhfkB2TX23EsBc',
    appId: '1:989557975107:web:fd7821ac477be09e860cf6',
    messagingSenderId: '989557975107',
    projectId: 'oceanpet-7055d',
    authDomain: 'oceanpet-7055d.firebaseapp.com',
    storageBucket: 'oceanpet-7055d.firebasestorage.app',
    measurementId: 'G-4BRWFGVTF1',
  );
}
